### ISSUE TITLE
Open the contract source code, an error occurs

### ISSUE THREAD

**Issue by leon8866** [aurora-is-near/bridge-assets#136]
Hello, I want to ask a question, I want to view the source code of this contract, but an error occurs, what is the reason?
https://explorer.mainnet.aurora.dev/address/0x802119e4e253D5C19aA06A5d567C5a41596D6803/contracts

**Comment by sept-en** [comment]
First, I'd say the correct repo for explorer-related issues will be https://github.com/aurora-is-near/blockscout
So please open an issue there.

Nevertheless, you can check the contract source code in Aurorascan: https://aurorascan.dev/address/0x802119e4e253D5C19aA06A5d567C5a41596D6803#code
